Description: >
  Cloudfront distribution for UdaPeople
Parameters:
  CTWorkflowID:
    Description: Unique identifier.
    Type: String

Resources:
  
  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Origin Access Identity for Static Website

  WebpageCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub "udapeople1-${CTWorkflowID}.s3-website-us-east-1.amazonaws.com"
            Id: webpage
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        Enabled: True
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: False
          TargetOriginId: webpage
          ViewerProtocolPolicy: allow-all

Outputs:
  CTWorkflowID:
    Value: !Sub ${CTWorkflowID}
    Description: URL for website hosted on S3
    Export:
      Name: CTWorkflowID